[lib]
crate-type = ["bin"]
path = "src-tauri/main.rs"

[package]
name = "snowtrail-app"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.2", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.2", features = ["shell-open"] }
tauri-plugin-store = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "dev" }
rss = "2.0"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
objc = "0.2.7"

[features]
default = ["custom-protocol"]
# tauri used this feature for production builds where `devPath` points to the filesystem
custom-protocol = ["tauri/custom-protocol"]
