[lib]
crate-type = ["bin"]
path = "src-tauri/main.rs"

[package]
name = "snowtrail-app"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.2.1", features = [] }

[dependencies]
serde_json = "1.0.94"
serde = { version = "1.0.158", features = ["derive"] }
tauri = { version = "1.2.4", features = ["shell-all"] }
rss = "2.0.2"
reqwest = { version = "0.11.15", features = ["json"] }
tokio = { version = "1.26.0", features = ["full"] }
objc = "0.2.7"
dirs = "5.0.0"
redis = "0.22.3"
rs-docker = "0.0.60"

[features]
default = ["custom-protocol"]
# tauri used this feature for production builds where `devPath` points to the filesystem
custom-protocol = ["tauri/custom-protocol"]
